/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.paz1c.databazaKnih.GUI;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JList;
import sk.upjs.ics.paz1c.databazaKnih.Author;
import sk.upjs.ics.paz1c.databazaKnih.AuthorManager;
import sk.upjs.ics.paz1c.databazaKnih.Book;
import sk.upjs.ics.paz1c.databazaKnih.BookManager;
import sk.upjs.ics.paz1c.databazaKnih.Genre;
import sk.upjs.ics.paz1c.databazaKnih.GenreManager;
import sk.upjs.ics.paz1c.databazaKnih.ObjectFactory;
import sk.upjs.ics.paz1c.databazaKnih.User;
/**
 *
 * @author szoplakz
 */
public class AddOrUpdateAuthorForm extends javax.swing.JDialog {
GenreManager genreManager = ObjectFactory.INSTANCE.getGenreManager();
AuthorManager authorManager = ObjectFactory.INSTANCE.getAuthorManager();
BookManager bookManager = ObjectFactory.INSTANCE.getBookManager();
private String[] genreNames;
private Genre[] genreArray;
private String[] bookNames;
private Book[] bookArray;
private Author author;

    /**
     * Creates new form AuthorRequestForm
     */
    public AddOrUpdateAuthorForm(java.awt.Dialog parent, boolean modal, Author author, boolean isUpdate) {
        super(parent, modal);
        initComponents();
        this.author = author; 
        List<Genre> genres = genreManager.getAllGenres();
             
             genreNames = new String[genres.size()];
             genreArray= new Genre[genres.size()];
             int i = 0;
            for (Genre genre : genres) {
               genreNames[i]= genre.getName();
               genreArray[i] = genre;
               i++;
            }
             GenreList.setListData(genreNames);
             
             List<Book> books = bookManager.getAllBooks();
             
             bookNames = new String[books.size()];
             bookArray= new Book[books.size()];
             int j = 0;
            for (Book book : books) {
               bookNames[j]= book.getName();
               bookArray[j] = book;
               j++;
            }
             BookList.setListData(bookNames);
            
        if(isUpdate){
        AddAuthorButton.enable(false);
        AddAuthorButton.setVisible(false);
        NameTextField.setText(author.getName());
        NationalityTextField.setText(author.getNationality());
        DateofBirthTextfield.setText(Integer.toString(author.getBirth()));
      
        if(author.getDeath()!=0){
            DateofDeathTextField.setText(Integer.toString(author.getDeath()));
        }
       
       
       
        if(author.getSex().equals("f")){
        GenderSelectComboBox.setSelectedIndex(1);
        }
        
        BiographyTextArea.setText(author.getBiography());
        
        
        
        } else {
         UpdateAuthorButton.enable(false);
        UpdateAuthorButton.setVisible(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AuthorNameLabel = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        NationalityTextField = new javax.swing.JTextField();
        NationalityLabel = new javax.swing.JLabel();
        DateofDeathLabel = new javax.swing.JLabel();
        DateofDeathTextField = new javax.swing.JTextField();
        DateofBirthTextfield = new javax.swing.JTextField();
        DateofBirthLabel = new javax.swing.JLabel();
        GenderSearchLabel = new javax.swing.JLabel();
        GenderSelectComboBox = new javax.swing.JComboBox<>();
        BookLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        GenreList = new javax.swing.JList<>();
        AddAuthorButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BiographyTextArea = new javax.swing.JTextArea();
        BiographyLabel = new javax.swing.JLabel();
        UpdateAuthorButton = new javax.swing.JButton();
        GenreLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        BookList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        AuthorNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AuthorNameLabel.setForeground(new java.awt.Color(0, 102, 204));
        AuthorNameLabel.setText("Name:");

        NationalityLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NationalityLabel.setForeground(new java.awt.Color(0, 102, 204));
        NationalityLabel.setText("Nationality:");

        DateofDeathLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DateofDeathLabel.setForeground(new java.awt.Color(0, 102, 204));
        DateofDeathLabel.setText("Date of Death:");

        DateofBirthLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DateofBirthLabel.setForeground(new java.awt.Color(0, 102, 204));
        DateofBirthLabel.setText("Date of Birth:");

        GenderSearchLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GenderSearchLabel.setForeground(new java.awt.Color(0, 102, 204));
        GenderSearchLabel.setText("Gender:");

        GenderSelectComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        GenderSelectComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderSelectComboBoxActionPerformed(evt);
            }
        });

        BookLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BookLabel.setForeground(new java.awt.Color(0, 102, 204));
        BookLabel.setText("Books:");

        GenreList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        GenreList.setName(""); // NOI18N
        jScrollPane2.setViewportView(GenreList);

        AddAuthorButton.setText("Add Author");
        AddAuthorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAuthorButtonActionPerformed(evt);
            }
        });

        BiographyTextArea.setColumns(20);
        BiographyTextArea.setRows(5);
        jScrollPane1.setViewportView(BiographyTextArea);

        BiographyLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BiographyLabel.setForeground(new java.awt.Color(0, 102, 204));
        BiographyLabel.setText("Biography:");

        UpdateAuthorButton.setText("Update Author");
        UpdateAuthorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateAuthorButtonActionPerformed(evt);
            }
        });

        GenreLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GenreLabel1.setForeground(new java.awt.Color(0, 102, 204));
        GenreLabel1.setText("Genres:");

        BookList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        BookList.setName(""); // NOI18N
        jScrollPane3.setViewportView(BookList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(UpdateAuthorButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NationalityTextField)
                    .addComponent(BiographyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateofDeathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1)
                    .addComponent(DateofDeathTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(NationalityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AuthorNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameTextField)
                            .addComponent(DateofBirthTextfield)
                            .addComponent(AddAuthorButton)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(GenderSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(GenderSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DateofBirthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(380, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(GenreLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(326, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NationalityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NationalityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DateofDeathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DateofDeathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BiographyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(UpdateAuthorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(AuthorNameLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)
                    .addComponent(DateofBirthLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(DateofBirthTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(GenderSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(GenderSelectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                    .addComponent(AddAuthorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(256, 256, 256)
                    .addComponent(GenreLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(397, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenderSelectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderSelectComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderSelectComboBoxActionPerformed

    private void AddAuthorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAuthorButtonActionPerformed
        Author newAuthor = new Author();
        newAuthor.setName(NameTextField.getText());
        newAuthor.setNationality(NationalityTextField.getText());
        newAuthor.setBirth(Integer.parseInt(DateofBirthTextfield.getText()));
        if(!DateofDeathTextField.getText().isEmpty()){
        newAuthor.setDeath(Integer.parseInt(DateofDeathTextField.getText()));
        }
        if(GenderSelectComboBox.getSelectedIndex()==0){
        newAuthor.setSex("m");
        } else {
        newAuthor.setSex("f");
        }
       
        GenreList.getSelectedIndices();
        int[] genreIndeces = GenreList.getSelectedIndices();
        List<Genre> genreList = new ArrayList<Genre>();
        for (int i = 0; i < genreIndeces.length; i++) {
            genreList.add(genreArray[genreIndeces[i]]);
            
        }
        
        BookList.getSelectedIndices();
        int[] bookIndeces = BookList.getSelectedIndices();
        List<Book> bookList = new ArrayList<Book>();
        for (int i = 0; i < bookIndeces.length; i++) {
            bookList.add(bookArray[genreIndeces[i]]);
            
        }
        newAuthor.setVerificationStatus(true);
        newAuthor.setGenres(genreList);
        authorManager.addGenresToAuthor(genreList, newAuthor);
        authorManager.addBooksToAuthor(bookList, newAuthor);
        newAuthor.setBiography(BiographyTextArea.getText());
        newAuthor.setIsActive(true);
        authorManager.insertAuthor(newAuthor);
        this.setVisible(false);
    }//GEN-LAST:event_AddAuthorButtonActionPerformed

    private void UpdateAuthorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateAuthorButtonActionPerformed
     
        author.setName(NameTextField.getText());
        author.setNationality(NationalityTextField.getText());
        author.setBirth(Integer.parseInt(DateofBirthTextfield.getText()));
        if(!DateofDeathTextField.getText().isEmpty()){
        author.setDeath(Integer.parseInt(DateofDeathTextField.getText()));
        }
        if(GenderSelectComboBox.getSelectedIndex()==0){
        author.setSex("m");
        } else {
        author.setSex("f");
        }
       
        GenreList.getSelectedIndices();
        int[] genreIndeces = GenreList.getSelectedIndices();
        List<Genre> genreList = new ArrayList<Genre>();
        for (int i = 0; i < genreIndeces.length; i++) {
            genreList.add(genreArray[genreIndeces[i]]);
            
        }
        
        BookList.getSelectedIndices();
        int[] bookIndeces = BookList.getSelectedIndices();
        List<Book> bookList = new ArrayList<Book>();
        for (int i = 0; i < bookIndeces.length; i++) {
            bookList.add(bookArray[genreIndeces[i]]);
            
        }
        author.setVerificationStatus(true);
        author.setGenres(genreList);
        authorManager.addGenresToAuthor(genreList, author);
        authorManager.addBooksToAuthor(bookList, author);
        author.setBiography(BiographyTextArea.getText());
        author.setIsActive(true);
        authorManager.insertAuthor(author);
        this.setVisible(false);
    }//GEN-LAST:event_UpdateAuthorButtonActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAuthorButton;
    private javax.swing.JLabel AuthorNameLabel;
    private javax.swing.JLabel BiographyLabel;
    private javax.swing.JTextArea BiographyTextArea;
    private javax.swing.JLabel BookLabel;
    private javax.swing.JList<String> BookList;
    private javax.swing.JLabel DateofBirthLabel;
    private javax.swing.JTextField DateofBirthTextfield;
    private javax.swing.JLabel DateofDeathLabel;
    private javax.swing.JTextField DateofDeathTextField;
    private javax.swing.JLabel GenderSearchLabel;
    private javax.swing.JComboBox<String> GenderSelectComboBox;
    private javax.swing.JLabel GenreLabel1;
    private javax.swing.JList<String> GenreList;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JLabel NationalityLabel;
    private javax.swing.JTextField NationalityTextField;
    private javax.swing.JButton UpdateAuthorButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
