/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.paz1c.databazaKnih.GUI;

import java.util.ArrayList;
import java.util.List;
import sk.upjs.ics.paz1c.databazaKnih.Author;
import sk.upjs.ics.paz1c.databazaKnih.AuthorManager;
import sk.upjs.ics.paz1c.databazaKnih.Book;
import sk.upjs.ics.paz1c.databazaKnih.BookManager;
import sk.upjs.ics.paz1c.databazaKnih.Genre;
import sk.upjs.ics.paz1c.databazaKnih.GenreManager;
import sk.upjs.ics.paz1c.databazaKnih.ObjectFactory;
import sk.upjs.ics.paz1c.databazaKnih.Tag;
import sk.upjs.ics.paz1c.databazaKnih.User;
import sk.upjs.ics.paz1c.databazaKnih.UserManager;

/**
 *
 * @author szoplakz
 */
public class AuthorForm extends javax.swing.JDialog {

    AuthorManager authorManager = ObjectFactory.INSTANCE.getAuthorManager();
    UserManager userManager = ObjectFactory.INSTANCE.getUserManager();
    GenreManager genreManager = ObjectFactory.INSTANCE.getGenreManager();
    BookManager bookManager = ObjectFactory.INSTANCE.getBookManager();
    private Author author;
    private User user;

    /**
     * Creates new form AuthorForm
     */
    public AuthorForm(java.awt.Dialog parent, boolean modal, Author author, User user) {
        super(parent, modal);
        initComponents();
        this.author = author;
        this.user = user;
        if (!user.isIsAdmin()) {
            UpdateButton.enable(false);
            UpdateButton.setVisible(false);
            DeleteButton.enable(false);
            DeleteButton.setVisible(false);
            ViewRequestsButton.enable(false);
            ViewRequestsButton.setVisible(false);
        }
        NameLabel.setText("Name: " + author.getName());
        if (author.getDeath() == 0) {
            LifeLabel.setText(author.getBirth() + " - ");

        } else {
            LifeLabel.setText(author.getBirth() + " - " + author.getDeath());
        }
        NationalityLabel.setText("Nationality: " + author.getNationality());
        GenderLabel.setText("Gender: " + author.getSex());

        List<Integer> genres = author.getGenres();
        String[] genreNames = new String[genres.size()];
        int i = 0;
        Genre genre;
        for (Integer genreId : genres) {
            genre = genreManager.findById(genreId);
            genreNames[i] = genre.getName();
            i++;
        }
        GenreList.setListData(genreNames);

        List<Integer> books = author.getBooks();
        String[] bookNames = new String[books.size()];
        int j = 0;
        Book book;;
        for (Integer bookId : books) {
            book = bookManager.findById(bookId);
            bookNames[j] = book.getName();

            j++;
        }
        BookList.setListData(bookNames);

        BiographyTextArea.setText(author.getBiography());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        GenreLabel = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        BiographyLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BiographyTextArea = new javax.swing.JTextArea();
        LifeLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        NationalityLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        GenreList = new javax.swing.JList<>();
        BooksLable = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        BookList = new javax.swing.JList<>();
        AddtoFavouritesLabel = new javax.swing.JLabel();
        AuthorReviewsLabel = new javax.swing.JLabel();
        AuthorReviewsIconButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        ReviewButton = new javax.swing.JButton();
        SendRequestButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        ViewRequestsButton = new javax.swing.JButton();
        AddToFavouritesToggleButton = new javax.swing.JToggleButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        GenreLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GenreLabel.setForeground(new java.awt.Color(0, 102, 204));
        GenreLabel.setText("Genres:");

        GenderLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GenderLabel.setForeground(new java.awt.Color(0, 102, 204));
        GenderLabel.setText("Gender:");

        BiographyLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BiographyLabel.setForeground(new java.awt.Color(0, 102, 204));
        BiographyLabel.setText("Biography:");

        BiographyTextArea.setColumns(20);
        BiographyTextArea.setRows(5);
        jScrollPane1.setViewportView(BiographyTextArea);

        LifeLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LifeLabel.setForeground(new java.awt.Color(0, 102, 204));
        LifeLabel.setText("???? - ????");

        NameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(0, 102, 204));
        NameLabel.setText("Name:");

        NationalityLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NationalityLabel.setForeground(new java.awt.Color(0, 102, 204));
        NationalityLabel.setText("Nationality:");

        GenreList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(GenreList);

        BooksLable.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BooksLable.setForeground(new java.awt.Color(0, 102, 204));
        BooksLable.setText("Books:");

        BookList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(BookList);

        AddtoFavouritesLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddtoFavouritesLabel.setForeground(new java.awt.Color(0, 102, 255));
        AddtoFavouritesLabel.setText("Add to favourites:");

        AuthorReviewsLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AuthorReviewsLabel.setForeground(new java.awt.Color(0, 102, 255));
        AuthorReviewsLabel.setText("Reviews:");

        AuthorReviewsIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/AuthorReviewIcon.png"))); // NOI18N
        AuthorReviewsIconButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthorReviewsIconButtonActionPerformed(evt);
            }
        });

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        ReviewButton.setText("Review");
        ReviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewButtonActionPerformed(evt);
            }
        });

        SendRequestButton.setText("Send Request");
        SendRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendRequestButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        ViewRequestsButton.setText("View Requests");
        ViewRequestsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewRequestsButtonActionPerformed(evt);
            }
        });

        AddToFavouritesToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/FavouriteAuthorsIcon.png"))); // NOI18N
        AddToFavouritesToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToFavouritesToggleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BooksLable, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AddtoFavouritesLabel)
                                    .addComponent(AddToFavouritesToggleButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AuthorReviewsLabel)
                                    .addComponent(AuthorReviewsIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(LifeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GenderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NationalityLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(GenreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(ViewRequestsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BiographyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SendRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReviewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SendRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BiographyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReviewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LifeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NationalityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GenderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GenreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewRequestsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BooksLable, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AuthorReviewsLabel)
                                .addGap(8, 8, 8)
                                .addComponent(AuthorReviewsIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddtoFavouritesLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddToFavouritesToggleButton)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AuthorReviewsIconButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthorReviewsIconButtonActionPerformed
        ListForm authorReviewsList = new ListForm(this, true, "AuthorReviews", null, null, author);
        authorReviewsList.setVisible(true);
    }//GEN-LAST:event_AuthorReviewsIconButtonActionPerformed

    private void ReviewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewButtonActionPerformed

        MyReviewForm reviewForm = new MyReviewForm(this, true, false, user, null, author);
        reviewForm.setVisible(true);
    }//GEN-LAST:event_ReviewButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        AddOrUpdateAuthorForm updateAuthorForm = new AddOrUpdateAuthorForm(this, true, author, true,user);
        updateAuthorForm.setVisible(true);
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        authorManager.deleteAuthor(author.getId());
        this.setVisible(false);
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void SendRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendRequestButtonActionPerformed
        MyRequestForm requestForm = new MyRequestForm(this, true, false, user, null, author);
        requestForm.setVisible(true);
    }//GEN-LAST:event_SendRequestButtonActionPerformed

    private void ViewRequestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewRequestsButtonActionPerformed
        ListForm authorReviewsList = new ListForm(this, true, "RequestsByAuthor", null, null, author);
        authorReviewsList.setVisible(true);

    }//GEN-LAST:event_ViewRequestsButtonActionPerformed

    private void AddToFavouritesToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToFavouritesToggleButtonActionPerformed
        if (AddToFavouritesToggleButton.isSelected()) {
            List<Integer> authors = new ArrayList<>();
            authors.add(author.getId());
            userManager.addFavoriteAuthorsToUser(authors, user);
        }
    }//GEN-LAST:event_AddToFavouritesToggleButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AddToFavouritesToggleButton;
    private javax.swing.JLabel AddtoFavouritesLabel;
    private javax.swing.JButton AuthorReviewsIconButton;
    private javax.swing.JLabel AuthorReviewsLabel;
    private javax.swing.JLabel BiographyLabel;
    private javax.swing.JTextArea BiographyTextArea;
    private javax.swing.JList<String> BookList;
    private javax.swing.JLabel BooksLable;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel GenreLabel;
    private javax.swing.JList<String> GenreList;
    private javax.swing.JLabel LifeLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel NationalityLabel;
    private javax.swing.JButton ReviewButton;
    private javax.swing.JButton SendRequestButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton ViewRequestsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
