/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.paz1c.databazaKnih.GUI;

import java.util.List;
import sk.upjs.ics.paz1c.databazaKnih.Book;
import sk.upjs.ics.paz1c.databazaKnih.BookManager;
import sk.upjs.ics.paz1c.databazaKnih.Genre;
import sk.upjs.ics.paz1c.databazaKnih.ObjectFactory;
import sk.upjs.ics.paz1c.databazaKnih.Tag;
import sk.upjs.ics.paz1c.databazaKnih.User;
import sk.upjs.ics.paz1c.databazaKnih.UserManager;

/**
 *
 * @author szoplakz
 */
public class BookForm extends javax.swing.JDialog {
    
    UserManager userManager = ObjectFactory.INSTANCE.getUserManager();
    BookManager bookManager = ObjectFactory.INSTANCE.getBookManager();
    private Book book;
    private User user;

    /**
     * Creates new form BookForm
     */
    public BookForm(java.awt.Dialog parent, boolean modal, User user, Book book) {
        super(parent, modal);
        initComponents();
        this.book = book;
        this.user = user;
        if(!user.isIsAdmin()){
        UpdateButton.enable(false);
        UpdateButton.setVisible(false);
        DeleteButton.enable(false);
        DeleteButton.setVisible(false);
        }  
        if(user.getFavoriteBooks().contains(book)){
        AddtoFavouritesToggleButton.setSelected(true);
        }
        if(user.getReadBooks().contains(book)){
        AddtoReadToggleButton.setSelected(true);
        }
        if(user.getWantedBooks().contains(book)){
        AddtoWantedToggleButton.setSelected(true);
        }
        
        BookNameLabel.setText("Name: " + book.getName());
        AuthorNameLabel.setText("Author: " + book.getAuthor());
        ISBNLabel.setText("ISBN: " + book.getISBN());
        YearLabel.setText("Year of publication: " + book.getYear());
        RatingLabel.setText("Rating: " + book.getBayesianAverage());
        
        List<Genre> genres = book.getGenres();
        String[] genreNames = new String[genres.size()];
        int i = 0;
            for (Genre genre : genres) {
               genreNames[i]= genre.getName();
        i++;
    }
      GenreList.setListData(genreNames);
     
      List<Tag> tags = book.getTags();
        String[] tagNames = new String[tags.size()];
        int j = 0;
            for (Tag tag : tags) {
               tagNames[j]= tag.getName();
        
        j++;
    }
     TagList.setListData(tagNames); 
     
     SynopsisTextArea.setText(book.getDescription());
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AuthorNameLabel = new javax.swing.JLabel();
        ISBNLabel = new javax.swing.JLabel();
        LengthLabel = new javax.swing.JLabel();
        YearLabel = new javax.swing.JLabel();
        GenreBookLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        GenreList = new javax.swing.JList<>();
        TagsBookLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TagList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        SynopsisTextArea = new javax.swing.JTextArea();
        SynopsisLabel = new javax.swing.JLabel();
        ReviewButton = new javax.swing.JButton();
        AddToFavoriteBooksLabel = new javax.swing.JLabel();
        AddToReadBooksLabel = new javax.swing.JLabel();
        AddToWantedBooksLabel = new javax.swing.JLabel();
        ReviewsLabel = new javax.swing.JLabel();
        BookReviewsIconButton = new javax.swing.JButton();
        BookNameLabel = new javax.swing.JLabel();
        RatingLabel = new javax.swing.JLabel();
        SendRequestButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        AddtoFavouritesToggleButton = new javax.swing.JToggleButton();
        AddtoWantedToggleButton = new javax.swing.JToggleButton();
        AddtoReadToggleButton = new javax.swing.JToggleButton();
        ViewRequestsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        AuthorNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AuthorNameLabel.setForeground(new java.awt.Color(0, 102, 255));
        AuthorNameLabel.setText("Author:");

        ISBNLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ISBNLabel.setForeground(new java.awt.Color(0, 102, 255));
        ISBNLabel.setText("ISBN:");

        LengthLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LengthLabel.setForeground(new java.awt.Color(0, 102, 255));
        LengthLabel.setText("Number of Pages:");

        YearLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        YearLabel.setForeground(new java.awt.Color(0, 102, 255));
        YearLabel.setText("Year of publication:");

        GenreBookLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GenreBookLabel.setForeground(new java.awt.Color(0, 102, 255));
        GenreBookLabel.setText("Genres:");

        GenreList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(GenreList);

        TagsBookLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        TagsBookLabel.setForeground(new java.awt.Color(0, 102, 255));
        TagsBookLabel.setText("Tags:");

        TagList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(TagList);

        SynopsisTextArea.setColumns(20);
        SynopsisTextArea.setRows(5);
        jScrollPane3.setViewportView(SynopsisTextArea);

        SynopsisLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SynopsisLabel.setForeground(new java.awt.Color(0, 102, 255));
        SynopsisLabel.setText("Synopsis: ");

        ReviewButton.setText("Review");
        ReviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewButtonActionPerformed(evt);
            }
        });

        AddToFavoriteBooksLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddToFavoriteBooksLabel.setForeground(new java.awt.Color(0, 102, 255));
        AddToFavoriteBooksLabel.setText(" Add to Favourites:");

        AddToReadBooksLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddToReadBooksLabel.setForeground(new java.awt.Color(0, 102, 255));
        AddToReadBooksLabel.setText("Add to Read:");

        AddToWantedBooksLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddToWantedBooksLabel.setForeground(new java.awt.Color(0, 102, 255));
        AddToWantedBooksLabel.setText("Add to Wanted:");

        ReviewsLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ReviewsLabel.setForeground(new java.awt.Color(0, 102, 255));
        ReviewsLabel.setText("Reviews:");

        BookReviewsIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/BookReviewsIcon.png"))); // NOI18N
        BookReviewsIconButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookReviewsIconButtonActionPerformed(evt);
            }
        });

        BookNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BookNameLabel.setForeground(new java.awt.Color(0, 102, 255));
        BookNameLabel.setText("Name: (bookname)");

        RatingLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RatingLabel.setForeground(new java.awt.Color(0, 102, 255));
        RatingLabel.setText("Ratings:");

        SendRequestButton.setText("Send Request");
        SendRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendRequestButtonActionPerformed(evt);
            }
        });

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        AddtoFavouritesToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/FavouriteIcon.png"))); // NOI18N
        AddtoFavouritesToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddtoFavouritesToggleButtonActionPerformed(evt);
            }
        });

        AddtoWantedToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/WantedBookIcon.png"))); // NOI18N
        AddtoWantedToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddtoWantedToggleButtonActionPerformed(evt);
            }
        });

        AddtoReadToggleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/TickIcon.png"))); // NOI18N
        AddtoReadToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddtoReadToggleButtonActionPerformed(evt);
            }
        });

        ViewRequestsButton.setText("View Requests");
        ViewRequestsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewRequestsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane3)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SynopsisLabel)
                                        .addGap(39, 39, 39))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ViewRequestsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SendRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ReviewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BookReviewsIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ReviewsLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AddToReadBooksLabel)
                                    .addComponent(AddtoReadToggleButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AddToWantedBooksLabel)
                                    .addComponent(AddtoWantedToggleButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AddToFavoriteBooksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddtoFavouritesToggleButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(AuthorNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RatingLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TagsBookLabel)
                                        .addComponent(GenreBookLabel)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1))
                                    .addComponent(LengthLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(YearLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                                    .addComponent(ISBNLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BookNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 44, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BookNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AuthorNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ISBNLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LengthLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(YearLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RatingLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GenreBookLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TagsBookLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewRequestsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ReviewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SendRequestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SynopsisLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(AddToReadBooksLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddtoReadToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(AddToWantedBooksLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(AddtoWantedToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(AddToFavoriteBooksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AddtoFavouritesToggleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ReviewsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BookReviewsIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookReviewsIconButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookReviewsIconButtonActionPerformed
         ListForm bookReviewsList = new ListForm(this, true, "BookReview", user, book, null);
        bookReviewsList.setVisible(true);
    }//GEN-LAST:event_BookReviewsIconButtonActionPerformed

    private void ReviewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewButtonActionPerformed
         MyReviewForm reviewForm = new MyReviewForm(this, true, true, user, book , null);
                 reviewForm.setVisible(true);
    }//GEN-LAST:event_ReviewButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        AddOrUpdateBookForm updateBookForm = new AddOrUpdateBookForm(this, true, book, true);
        updateBookForm.setVisible(true);
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void SendRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendRequestButtonActionPerformed
       MyRequestForm requestForm = new MyRequestForm(this, true, true, user, book , null);
                 requestForm.setVisible(true);
    }//GEN-LAST:event_SendRequestButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        bookManager.deleteBook(book.getId());
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void AddtoFavouritesToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddtoFavouritesToggleButtonActionPerformed
        if(AddtoFavouritesToggleButton.isSelected()){
        userManager.addFavoriteBookToUser(book, user);
        } else {
        userManager.deleteFavoriteBookFromUser(book, user);
        }
    }//GEN-LAST:event_AddtoFavouritesToggleButtonActionPerformed

    private void AddtoWantedToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddtoWantedToggleButtonActionPerformed
        if(AddtoWantedToggleButton.isSelected()){
        userManager.addWantedBookToUser(book, user);
        } else {
        userManager.deleteWantedBookFromUser(book, user);
        }
    }//GEN-LAST:event_AddtoWantedToggleButtonActionPerformed

    private void AddtoReadToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddtoReadToggleButtonActionPerformed
        if(AddtoReadToggleButton.isSelected()){
        userManager.addReadBookToUser(book, user);
        } else {
        userManager.deleteReadBookFromUser(book, user);
        }
    }//GEN-LAST:event_AddtoReadToggleButtonActionPerformed

    private void ViewRequestsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewRequestsButtonActionPerformed
        ListForm authorReviewsList = new ListForm(this, true, "RequestsByBook", null,book,null);
        authorReviewsList.setVisible(true);

    }//GEN-LAST:event_ViewRequestsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddToFavoriteBooksLabel;
    private javax.swing.JLabel AddToReadBooksLabel;
    private javax.swing.JLabel AddToWantedBooksLabel;
    private javax.swing.JToggleButton AddtoFavouritesToggleButton;
    private javax.swing.JToggleButton AddtoReadToggleButton;
    private javax.swing.JToggleButton AddtoWantedToggleButton;
    private javax.swing.JLabel AuthorNameLabel;
    private javax.swing.JLabel BookNameLabel;
    private javax.swing.JButton BookReviewsIconButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel GenreBookLabel;
    private javax.swing.JList<String> GenreList;
    private javax.swing.JLabel ISBNLabel;
    private javax.swing.JLabel LengthLabel;
    private javax.swing.JLabel RatingLabel;
    private javax.swing.JButton ReviewButton;
    private javax.swing.JLabel ReviewsLabel;
    private javax.swing.JButton SendRequestButton;
    private javax.swing.JLabel SynopsisLabel;
    private javax.swing.JTextArea SynopsisTextArea;
    private javax.swing.JList<String> TagList;
    private javax.swing.JLabel TagsBookLabel;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton ViewRequestsButton;
    private javax.swing.JLabel YearLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
