/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.paz1c.databazaKnih.GUI;

import sk.upjs.ics.paz1c.databazaKnih.ObjectFactory;
import sk.upjs.ics.paz1c.databazaKnih.User;
import sk.upjs.ics.paz1c.databazaKnih.UserManager;

/**
 *
 * @author szoplakz
 */
public class ChangePassWordForm extends javax.swing.JDialog {
    private User user;
    private UserManager userManager;
    /**
     * Creates new form ChangePassWordForm
     */
    public ChangePassWordForm(java.awt.Dialog parent, boolean modal, User user) {
        super(parent, modal);
        initComponents();
        UserManager userManager = ObjectFactory.INSTANCE.getUserManager();
        this.user = user;
        this.userManager = userManager;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EnterPasswordLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        RepeatPasswordLabel = new javax.swing.JLabel();
        ConfirmPasswordField = new javax.swing.JPasswordField();
        AcceptChangesButton = new javax.swing.JButton();
        EnterOldPasswordLabel = new javax.swing.JLabel();
        OldPasswordField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        EnterPasswordLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EnterPasswordLabel.setForeground(new java.awt.Color(0, 102, 255));
        EnterPasswordLabel.setText("Enter New Password:");

        RepeatPasswordLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RepeatPasswordLabel.setForeground(new java.awt.Color(0, 102, 255));
        RepeatPasswordLabel.setText("Repeat New Password:");

        ConfirmPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPasswordFieldActionPerformed(evt);
            }
        });

        AcceptChangesButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AcceptChangesButton.setText("Confirm changes");
        AcceptChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptChangesButtonActionPerformed(evt);
            }
        });

        EnterOldPasswordLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EnterOldPasswordLabel.setForeground(new java.awt.Color(0, 102, 255));
        EnterOldPasswordLabel.setText("Enter Old Password:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RepeatPasswordLabel)
                    .addComponent(EnterPasswordLabel))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(OldPasswordField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(ConfirmPasswordField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EnterOldPasswordLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AcceptChangesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(EnterOldPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OldPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(EnterPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RepeatPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AcceptChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmPasswordFieldActionPerformed

    private void AcceptChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptChangesButtonActionPerformed
        String text = String.copyValueOf(OldPasswordField.getPassword());
        if(OldPasswordField.getText().isEmpty()){
            ErrorForm errorForm = new ErrorForm(this, true,"You must enter your old password!");
        errorForm.setVisible(true);
        return;
       } 
        String psswd = String.copyValueOf(PasswordField.getPassword());
        String cnfrm = String.copyValueOf(PasswordField.getPassword());
       if(!userManager.checkNameAndPassword(user.getUserName(), OldPasswordField.getText())){
       ErrorForm errorForm = new ErrorForm(this, true,"Your old password is incorrect !");
        errorForm.setVisible(true);
        return;
       }
        
        if(PasswordField.getText().isEmpty()){
            ErrorForm errorForm = new ErrorForm(this, true,"You must enter a new password!");
        errorForm.setVisible(true);
        return;
       }
        if(!psswd.equals(cnfrm)){
        ErrorForm errorForm = new ErrorForm(this, true,"Your initial and repeated password do not match !");
        errorForm.setVisible(true); 
        return; 
        
    }
        
        userManager.changePassword(user, psswd);
        this.setVisible(false);
        

    }//GEN-LAST:event_AcceptChangesButtonActionPerformed

    
   
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptChangesButton;
    private javax.swing.JPasswordField ConfirmPasswordField;
    private javax.swing.JLabel EnterOldPasswordLabel;
    private javax.swing.JLabel EnterPasswordLabel;
    private javax.swing.JPasswordField OldPasswordField;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel RepeatPasswordLabel;
    // End of variables declaration//GEN-END:variables
}
