/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.paz1c.databazaKnih.GUI;

import sk.upjs.ics.paz1c.databazaKnih.ObjectFactory;
import sk.upjs.ics.paz1c.databazaKnih.User;
import sk.upjs.ics.paz1c.databazaKnih.UserManager;

/**
 *
 * @author szoplakz
 */
public class RegisterForm extends javax.swing.JDialog {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateAccountButton = new javax.swing.JButton();
        SurnameTextField = new javax.swing.JTextField();
        EnterSurnameLabel = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        EnterNameLabel = new javax.swing.JLabel();
        EmailTextField = new javax.swing.JTextField();
        EnterEmailLabel = new javax.swing.JLabel();
        ConfirmPasswordField = new javax.swing.JPasswordField();
        RepeatPasswordLabel = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        EnterPasswordLabel = new javax.swing.JLabel();
        UsernameTextField = new javax.swing.JTextField();
        EnterUserNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        CreateAccountButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CreateAccountButton.setText("Create account");
        CreateAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccountButtonActionPerformed(evt);
            }
        });

        EnterSurnameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EnterSurnameLabel.setForeground(new java.awt.Color(0, 102, 255));
        EnterSurnameLabel.setText("Enter Surname(Optional):");

        EnterNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EnterNameLabel.setForeground(new java.awt.Color(0, 102, 255));
        EnterNameLabel.setText("Enter Name(Optional):");

        EnterEmailLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EnterEmailLabel.setForeground(new java.awt.Color(0, 102, 255));
        EnterEmailLabel.setText("Enter E-mail:");

        ConfirmPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPasswordFieldActionPerformed(evt);
            }
        });

        RepeatPasswordLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RepeatPasswordLabel.setForeground(new java.awt.Color(0, 102, 255));
        RepeatPasswordLabel.setText("Repeat Password:");

        EnterPasswordLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EnterPasswordLabel.setForeground(new java.awt.Color(0, 102, 255));
        EnterPasswordLabel.setText("Enter Password:");

        UsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextFieldActionPerformed(evt);
            }
        });

        EnterUserNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EnterUserNameLabel.setForeground(new java.awt.Color(0, 102, 255));
        EnterUserNameLabel.setText("Enter Username:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(UsernameTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(EmailTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConfirmPasswordField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PasswordField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EnterUserNameLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EnterEmailLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SurnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RepeatPasswordLabel)
                            .addComponent(EnterPasswordLabel)
                            .addComponent(EnterNameLabel)
                            .addComponent(EnterSurnameLabel)
                            .addComponent(CreateAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 40, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EnterUserNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EnterPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RepeatPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ConfirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EnterEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EnterNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EnterSurnameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SurnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(CreateAccountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmPasswordFieldActionPerformed

    private void UsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextFieldActionPerformed

    private void CreateAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccountButtonActionPerformed
       UserManager userManager = ObjectFactory.INSTANCE.getUserManager();
        
        if(UsernameTextField.getText().isEmpty()){
       ErrorForm errorForm = new ErrorForm(this, true,"You must enter a username to register !");
        errorForm.setVisible(true); 
        return;
       }
        if(PasswordField.getText().isEmpty()){
            ErrorForm errorForm = new ErrorForm(this, true,"You must enter a password to register !");
        errorForm.setVisible(true);
        return;
       }
        if(!PasswordField.getText().equals(ConfirmPasswordField.getText())){
        ErrorForm errorForm = new ErrorForm(this, true,"Your initial and repeated password do not match !");
        errorForm.setVisible(true); 
        return;  
    }//GEN-LAST:event_CreateAccountButtonActionPerformed
    if(EmailTextField.getText().isEmpty()){
     ErrorForm errorForm = new ErrorForm(this, true,"You must enter your e-mail register !");
        errorForm.setVisible(true);  
        return;
    }
    User user = new User();
    user.setUserName(UsernameTextField.getText());
    user.setPassword(PasswordField.getText());
    user.setMail(EmailTextField.getText());
    user.setName(NameTextField.getText());
    user.setSurname(SurnameTextField.getText());
    userManager.insertUser(user);
    ErrorForm errorForm = new ErrorForm(this, true,"Your account has been successfully created!");
    errorForm.setVisible(true);
    this.setVisible(false);
    } 
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmPasswordField;
    private javax.swing.JButton CreateAccountButton;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JLabel EnterEmailLabel;
    private javax.swing.JLabel EnterNameLabel;
    private javax.swing.JLabel EnterPasswordLabel;
    private javax.swing.JLabel EnterSurnameLabel;
    private javax.swing.JLabel EnterUserNameLabel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel RepeatPasswordLabel;
    private javax.swing.JTextField SurnameTextField;
    private javax.swing.JTextField UsernameTextField;
    // End of variables declaration//GEN-END:variables

    
}
