/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sk.upjs.ics.paz1c.GUI;

import javax.swing.JFrame;

/**
 *
 * @author szoplakz
 */
public class MyUserProfileForm extends javax.swing.JDialog {
    
    private static int MyId;
    private static boolean isAdmin;

    /**
     * Creates new form MyUserProfileForm
     */
    public MyUserProfileForm(java.awt.Frame parent, boolean modal){
    super(parent, modal);
        initComponents();
    }
    
    
    public MyUserProfileForm(java.awt.Frame parent, boolean modal, int MyId, String username, String name, String surname, String mail, boolean isAdmin) {
        super(parent, modal);
        initComponents();
        MyId=this.MyId;
        isAdmin=this.isAdmin;
        WelcomeUsernameLabel.setText("Welcome " + username + " !");
        FullNameLabel.setText("Full name: " + name + surname);
        EmailLabel.setText("E-mail: " + mail);
        if(isAdmin){
        StatusLabel.setText("Status: Admin");
        InspectRequestsButton.enable(true);
        } else {
        StatusLabel.setText("Status: User");
        InspectRequestsButton.enable(false);
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchButton = new javax.swing.JButton();
        SearchComboBox = new javax.swing.JComboBox<>();
        SearchLabelLine1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ManageProfileButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();
        DeleteProfileButton = new javax.swing.JButton();
        WantedBooksIconButton = new javax.swing.JButton();
        WantedBooksLabel = new javax.swing.JLabel();
        FavouriteReviewersLabel = new javax.swing.JLabel();
        FavouriteReviewersIconButton = new javax.swing.JButton();
        FriendsIconButton = new javax.swing.JButton();
        FriendsLabel = new javax.swing.JLabel();
        ReadBooksIconButton = new javax.swing.JButton();
        ReadBooksLabel = new javax.swing.JLabel();
        FavoriteBooksLabel = new javax.swing.JLabel();
        FavouriteBookIconButton = new javax.swing.JButton();
        FavouriteAuthorsLabel = new javax.swing.JLabel();
        FavouriteAuthorsIconButton = new javax.swing.JButton();
        InspectRequestsButton = new javax.swing.JButton();
        InspectRequests = new javax.swing.JLabel();
        AuthorReviewsButton = new javax.swing.JButton();
        AuthorReviewsLabel = new javax.swing.JLabel();
        BookReviewsButton = new javax.swing.JButton();
        BookReviewsLabel = new javax.swing.JLabel();
        MyReviewsLabel = new javax.swing.JLabel();
        StatusLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        FullNameLabel = new javax.swing.JLabel();
        WelcomeUsernameLabel = new javax.swing.JLabel();
        BookIconLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        SearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/SearchIcon.png"))); // NOI18N
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        SearchComboBox.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        SearchComboBox.setForeground(new java.awt.Color(0, 102, 204));
        SearchComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Books", "Authors", "Users" }));

        SearchLabelLine1.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        SearchLabelLine1.setForeground(new java.awt.Color(0, 0, 102));
        SearchLabelLine1.setText("Search for your favourite books, authors");

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("and users here !");

        ManageProfileButton.setText("Manage Profile");

        LogoutButton.setText("Logout");

        DeleteProfileButton.setText("Delete Profile");

        WantedBooksIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/WantedBookIcon.png"))); // NOI18N

        WantedBooksLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        WantedBooksLabel.setForeground(new java.awt.Color(0, 102, 255));
        WantedBooksLabel.setText("Wanted Books:");

        FavouriteReviewersLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FavouriteReviewersLabel.setForeground(new java.awt.Color(0, 102, 255));
        FavouriteReviewersLabel.setText("Favourite Reviewers:");

        FavouriteReviewersIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/FavouriteReviewersIcon.png"))); // NOI18N

        FriendsIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/FriendsIcon.png"))); // NOI18N
        FriendsIconButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FriendsIconButtonActionPerformed(evt);
            }
        });

        FriendsLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FriendsLabel.setForeground(new java.awt.Color(0, 102, 255));
        FriendsLabel.setText("Friends:");

        ReadBooksIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/TickIcon.png"))); // NOI18N

        ReadBooksLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ReadBooksLabel.setForeground(new java.awt.Color(0, 102, 255));
        ReadBooksLabel.setText("Read Books:");

        FavoriteBooksLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FavoriteBooksLabel.setForeground(new java.awt.Color(0, 102, 255));
        FavoriteBooksLabel.setText(" Favourite Books:");

        FavouriteBookIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/FavouriteIcon.png"))); // NOI18N

        FavouriteAuthorsLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FavouriteAuthorsLabel.setForeground(new java.awt.Color(0, 102, 255));
        FavouriteAuthorsLabel.setText("Favourite Authors:");

        FavouriteAuthorsIconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/FavouriteAuthorsIcon.png"))); // NOI18N

        InspectRequestsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/InspectRequestsIcon.png"))); // NOI18N

        InspectRequests.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        InspectRequests.setForeground(new java.awt.Color(0, 102, 255));
        InspectRequests.setText("Inspect Requests:");

        AuthorReviewsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/AuthorReviewIcon.png"))); // NOI18N

        AuthorReviewsLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AuthorReviewsLabel.setForeground(new java.awt.Color(0, 102, 255));
        AuthorReviewsLabel.setText("Authors:");

        BookReviewsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/BookReviewsIcon.png"))); // NOI18N

        BookReviewsLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BookReviewsLabel.setForeground(new java.awt.Color(0, 102, 255));
        BookReviewsLabel.setText("Books:");

        MyReviewsLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MyReviewsLabel.setForeground(new java.awt.Color(0, 102, 255));
        MyReviewsLabel.setText("My Reviews:");

        StatusLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        StatusLabel.setForeground(new java.awt.Color(0, 102, 255));
        StatusLabel.setText("Status: (User or Admin)");

        EmailLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(0, 102, 255));
        EmailLabel.setText("E-mail: (EmailHere)");

        FullNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FullNameLabel.setForeground(new java.awt.Color(0, 102, 255));
        FullNameLabel.setText("Full Name: (NameSurnameHere)");

        WelcomeUsernameLabel.setFont(new java.awt.Font("Pristina", 3, 18)); // NOI18N
        WelcomeUsernameLabel.setForeground(new java.awt.Color(0, 0, 102));
        WelcomeUsernameLabel.setText("Welcome (UserNameHere) !");

        BookIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Obrazky/kniha4.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(633, Short.MAX_VALUE)
                .addComponent(BookIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(BookReviewsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BookReviewsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AuthorReviewsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(EmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(StatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                                .addComponent(MyReviewsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SearchLabelLine1)
                                .addComponent(jLabel2)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(SearchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(50, 50, 50)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ManageProfileButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(LogoutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DeleteProfileButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(InspectRequestsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(InspectRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(55, 55, 55)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(FavouriteBookIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(96, 96, 96)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ReadBooksLabel)
                                        .addComponent(ReadBooksIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(FavouriteAuthorsIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(96, 96, 96)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(FriendsLabel)
                                        .addComponent(FriendsIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(FavouriteAuthorsLabel)
                                .addComponent(FavoriteBooksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(FavouriteReviewersLabel)
                                    .addGap(9, 9, 9))
                                .addComponent(FavouriteReviewersIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(WantedBooksIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(WantedBooksLabel)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AuthorReviewsLabel)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(WelcomeUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(FullNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BookIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(555, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(WelcomeUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FullNameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(SearchButton)
                                    .addGap(4, 4, 4)
                                    .addComponent(SearchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(EmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(StatusLabel)
                                            .addGap(18, 18, 18)
                                            .addComponent(MyReviewsLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(BookReviewsLabel)
                                            .addGap(11, 11, 11)
                                            .addComponent(BookReviewsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(ManageProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(34, 34, 34)
                                            .addComponent(DeleteProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(AuthorReviewsLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(AuthorReviewsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(SearchLabelLine1)
                                    .addGap(28, 28, 28)
                                    .addComponent(jLabel2)))
                            .addGap(19, 19, 19)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(FavoriteBooksLabel)
                                        .addComponent(ReadBooksLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ReadBooksIconButton, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                        .addComponent(FavouriteBookIconButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(InspectRequests)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(InspectRequestsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(397, 397, 397)
                            .addComponent(WantedBooksLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(WantedBooksIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FriendsLabel)
                        .addComponent(FavouriteAuthorsLabel)
                        .addComponent(FavouriteReviewersLabel))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(FavouriteReviewersIconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FriendsIconButton)
                        .addComponent(FavouriteAuthorsIconButton))
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        if (SearchComboBox.getSelectedItem()=="Books"){
            BookSearchForm bookSearchForm = new BookSearchForm(this, true, MyId, isAdmin);
            bookSearchForm.setVisible(true);
        }
        if (SearchComboBox.getSelectedItem()=="Authors"){
            AuthorSearchForm authorSearchForm = new AuthorSearchForm(this, true, MyId, isAdmin);
            authorSearchForm.setVisible(true);
        }
        if (SearchComboBox.getSelectedItem()=="Users"){
            UserSearchForm userSearchForm = new UserSearchForm(this, true, this.MyId, isAdmin);
            userSearchForm.setVisible(true);
    }//GEN-LAST:event_SearchButtonActionPerformed
    }
    private void FriendsIconButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FriendsIconButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FriendsIconButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AuthorReviewsButton;
    private javax.swing.JLabel AuthorReviewsLabel;
    private javax.swing.JLabel BookIconLabel;
    private javax.swing.JButton BookReviewsButton;
    private javax.swing.JLabel BookReviewsLabel;
    private javax.swing.JButton DeleteProfileButton;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel FavoriteBooksLabel;
    private javax.swing.JButton FavouriteAuthorsIconButton;
    private javax.swing.JLabel FavouriteAuthorsLabel;
    private javax.swing.JButton FavouriteBookIconButton;
    private javax.swing.JButton FavouriteReviewersIconButton;
    private javax.swing.JLabel FavouriteReviewersLabel;
    private javax.swing.JButton FriendsIconButton;
    private javax.swing.JLabel FriendsLabel;
    private javax.swing.JLabel FullNameLabel;
    private javax.swing.JLabel InspectRequests;
    private javax.swing.JButton InspectRequestsButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton ManageProfileButton;
    private javax.swing.JLabel MyReviewsLabel;
    private javax.swing.JButton ReadBooksIconButton;
    private javax.swing.JLabel ReadBooksLabel;
    private javax.swing.JButton SearchButton;
    private javax.swing.JComboBox<String> SearchComboBox;
    private javax.swing.JLabel SearchLabelLine1;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JButton WantedBooksIconButton;
    private javax.swing.JLabel WantedBooksLabel;
    private javax.swing.JLabel WelcomeUsernameLabel;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
